[project]
name = "openlogrca"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.3.4",
    "fastapi>=0.121.2",
    "rich>=14.2.0",
]
